name: Screaming Frog Crawl Automation

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the `main` branch
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub UI

jobs:
  crawl:
    runs-on: macos-latest  # This ensures the workflow runs on GitHub's MacOS virtual environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This checks out your repository to the GitHub runner

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  # Install Homebrew package manager

      - name: Install Screaming Frog SEO Tool
        run: |
          brew install screamingfrog-seo-spider  # Install Screaming Frog SEO Spider using Homebrew

      - name: Run Screaming Frog Crawl
        run: |
          screamingfrogseotool --crawl https://yourwebsite.com --output ./results  # Replace with your website URL and desired output folder

      - name: Upload Crawl Results as Artifact
        uses: actions/upload-artifact@v3  # Uploads the crawl results so you can download them from the GitHub UI
        with:
          name: crawl-results
          path: ./results  # This path stores the crawl results
